# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- production

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '7dbc0df4-28f2-426f-a342-6fb0a0ff6c8c'
  imageRepository: 'integra-backend'
  containerRegistry: 'integraproductionapi.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Azure Pipelines
    #Your build pipeline references an undefined variable named ‘mySecureFile.secureFilePath’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure Container Registry'
      inputs:
        azureSubscription: 'Pay-As-You-Go (5ad7adcb-77e7-484e-8d53-3655a18e87ed)'
        resourceGroupName: 'integraproductionapi-rg'
        location: 'South Central US'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/Microsoft/devops-project-samples/057f6cc268a62922d012067d069d58684e967d0a/armtemplates/webapp-containers/containerRegistry-template.json'
        overrideParameters: '-registryName "integraProductionAPIacr" -registryLocation "South Central US" -registrySku "Standard"'

    - task: DownloadSecureFile@1
      displayName: 'Download secure file'
      inputs:
        secureFile: 'd4e2854f-e14f-42e0-b4e8-e32055cb3375'

    - task: CopyFiles@2
      displayName: 'Copy Files from $(Agent.TempDirectory) to $(Build.SourcesDirectory)'
      inputs:
        SourceFolder: '$(Agent.TempDirectory)'
        Contents: '$(mySecureFile.secureFilePath)'
        TargetFolder: '$(Build.SourcesDirectory)'

    - task: Docker@1
      displayName: 'Build an image'
      inputs:
        azureSubscriptionEndpoint: 'Pay-As-You-Go (5ad7adcb-77e7-484e-8d53-3655a18e87ed)'
        azureContainerRegistry: integraproductionapi.azurecr.io
        imageName: 'integra-backend'
        includeLatestTag: true

    - task: Docker@1
      displayName: 'Push an image'
      inputs:
        azureSubscriptionEndpoint: 'Pay-As-You-Go (5ad7adcb-77e7-484e-8d53-3655a18e87ed)'
        azureContainerRegistry: integraproductionapi.azurecr.io
        command: 'Push an image'
        imageName: 'integra-backend:latest'
